<?php
/**
 * Database connection (PDO) and query helpers.
 *
 * Was: mysqli_connect("localhost", "root", "", "royal_express_db") or die(...)
 *
 * Now a single lazily-created PDO handle with exceptions enabled and emulated
 * prepares switched off, so placeholders are bound server-side and query text
 * can never be confused with data.
 */

require_once dirname(dirname(__DIR__)) . '/includes/logger.php';

/**
 * Credentials come from a config file kept outside the web root, so they are
 * never served over HTTP and never travel with the application source.
 * Environment variables override it; the defaults are a last resort.
 */
if (!defined('DB_HOST')) {

    require_once dirname(dirname(__DIR__)) . '/includes/private_path.php';

    $configPath = RE_PRIVATE_DIR . '/db.php';
    $config = is_readable($configPath) ? require $configPath : array();

    define('DB_HOST', getenv('DB_HOST') ?: (isset($config['host']) ? $config['host'] : 'localhost'));
    define('DB_NAME', getenv('DB_NAME') ?: (isset($config['name']) ? $config['name'] : 'royal_express_db'));
    define('DB_USER', getenv('DB_USER') ?: (isset($config['user']) ? $config['user'] : 'root'));
    define('DB_PASS', getenv('DB_PASS') !== false ? getenv('DB_PASS') : (isset($config['pass']) ? $config['pass'] : ''));

    unset($config, $configPath);
}

if (!function_exists('db')) {

    // Internal failures are logged, never rendered into the response.
    ini_set('display_errors', '0');
    ini_set('log_errors', '1');
    error_reporting(E_ALL);

    /**
     * Holds the rows of a SELECT so the call sites can keep using the same
     * fetch-in-a-loop shape they used with mysqli.
     */
    class DbResult
    {
        private $rows;
        private $cursor = 0;

        public function __construct(array $rows)
        {
            $this->rows = $rows;
        }

        public function fetch()
        {
            if ($this->cursor >= count($this->rows)) {
                return false;
            }
            return $this->rows[$this->cursor++];
        }

        public function all()
        {
            return $this->rows;
        }

        public function count()
        {
            return count($this->rows);
        }
    }

    /**
     * @return PDO shared handle for the life of the request
     */
    function db()
    {
        static $pdo = null;

        if ($pdo === null) {
            $dsn = 'mysql:host=' . DB_HOST . ';dbname=' . DB_NAME . ';charset=utf8mb4';
            try {
                $pdo = new PDO($dsn, DB_USER, DB_PASS, array(
                    PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
                    PDO::ATTR_EMULATE_PREPARES   => false,
                    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                ));
            } catch (Throwable $e) {
                // Full detail to the log, generic text to the browser.
                $message = log_internal_error('DB connect', $e);
                http_response_code(500);
                exit($message);
            }
        }

        return $pdo;
    }

    /**
     * Run a SELECT with bound parameters.
     *
     * @param string $sql    query text containing ? or :named placeholders
     * @param array  $params values to bind
     * @return DbResult
     */
    function db_select($sql, array $params = array())
    {
        try {
            $stmt = db()->prepare($sql);
            $stmt->execute($params);
            return new DbResult($stmt->fetchAll());
        } catch (Throwable $e) {
            log_internal_error('Query failed: ' . $sql, $e);
            return new DbResult(array());
        }
    }

    /**
     * Run an INSERT / UPDATE / DELETE with bound parameters.
     *
     * @return bool whether the statement executed
     */
    function db_exec($sql, array $params = array())
    {
        try {
            $stmt = db()->prepare($sql);
            return $stmt->execute($params);
        } catch (Throwable $e) {
            log_internal_error('Statement failed: ' . $sql, $e);
            return false;
        }
    }

    /**
     * Id generated by the most recent INSERT.
     */
    function db_last_insert_id()
    {
        return db()->lastInsertId();
    }

    // --- result accessors -------------------------------------------------
    // These replace mysqli_fetch_assoc / mysqli_num_rows / mysqli_fetch_all
    // one-for-one at the call sites.

    function db_fetch($result)
    {
        return ($result instanceof DbResult) ? $result->fetch() : false;
    }

    function db_num_rows($result)
    {
        return ($result instanceof DbResult) ? $result->count() : 0;
    }

    function db_fetch_all($result)
    {
        return ($result instanceof DbResult) ? $result->all() : array();
    }
}

$pdo = db();
